---
provisioner:
  inventory:
    group_vars:
      all:
        cadvisor_binary_local_dir: "/tmp"
        cadvisor_port: "8000"
        go_arch: amd64
        cadvisor_version: 0.47.0
        cadvisor_enable_metrics:
          - tcp
          - memory
          - network
          - cpu
        cadvisor_docker_only: true
