---
- name: Restart alertmanager
  listen: "restart alertmanager"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: alertmanager
    state: restarted
  register: alertmanager_restarted

- name: Reload alertmanager
  listen: "reload alertmanager"
  become: true
  ansible.builtin.systemd:
    name: alertmanager
    state: reloaded
  when: alertmanager_restarted is not defined
