---
- name: Configure NGINX reverse proxy
  hosts: target_servers
  become: yes
  vars:
    domen: "nginx.helm.uz"
    port: "3000"

  tasks:
    - name: Create NGINX configuration in sites-available
      copy:
        dest: /etc/nginx/sites-available/{{ domen }}.conf
        content: |
          server {
              listen 80;
              server_name {{ domen }} www.{{ domen }};
              
              location / {
                  proxy_pass http://localhost:{{ port }};
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
        mode: '0644'

    - name: Create symbolic link in sites-enabled
      file:
        src: /etc/nginx/sites-available/{{ domen }}.conf
        dest: /etc/nginx/sites-enabled/{{ domen }}.conf
        state: link
        force: yes

    - name: Reload NGINX to apply new configuration
      service:
        name: nginx
        state: reloaded