---
- name: Configure NGINX as a reverse proxy using nginxinc.nginx role
  hosts: nginx_servers
  become: yes
  roles:
    - role: nginxinc.nginx
      vars:
        nginx_http_template_enable: true  # Enable HTTP templates
        nginx_http_template_conf: |
          server {
              listen 80;
              server_name {{ domain_name }};
              
              location / {
                  proxy_pass http://{{ backend_server }};
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }