---
- name: Install and configure Prometheus
  hosts: prometheus_servers
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - prometheus

- name: Install and configure Node Exporter
  hosts: target_servers
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - node_exporter

- name: Install and configure Alert Manager
  hosts: target_servers
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - alertmanager
  vars:
    alertmanager_version: latest
    alertmanager_receivers:
      - name: discord
        webhook_configs:
          - send_resolved: true
            url: "https://discord.com/api/webhooks/1156904139327017063/UYC-Az12KeFyvpv2nEm_yvo_Ype0yvqenAxJNeNvTLUnN6hH-9p6YBc6jKJOKFWmlUTb"
    alertmanager_route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
      receiver: discord

- name: Install and configure Bind Exporter
  hosts: target_servers
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - bind_exporter

- name: Install and configure Blackbox Exporter
  hosts: target_servers
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - blackbox_exporter

- name: Install and configure cadvisor
  hosts: target_servers
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - cadvisor

- name: Install and configure chrony_exporter
  hosts: target_servers
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - chrony_exporter

- name: Install and configure fail2ban_exporter
  hosts: target_servers
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - fail2ban_exporter

- name: Install and configure ipmi_exporter
  hosts: target_servers
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - ipmi_exporter

- name: Install and configure memcached_exporter
  hosts: target_servers
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - memcached_exporter

- name: Install and configure mongodb_exporter
  hosts: target_servers
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - mongodb_exporter

- name: Install and configure mysqld exporter
  hosts: target_servers
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - mysqld_exporter

- name: Install and configure nginx_exporter
  hosts: target_servers
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - nginx_exporter

- name: Install and configure PostgreSQL exporter
  hosts: target_servers
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - postgres_exporter

- name: Install and configure process_exporter
  hosts: target_servers
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - process_exporter

- name: Install and configure pushgateway
  hosts: target_servers
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - pushgateway

- name: Install and configure redis_exporter
  hosts: target_servers
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - redis_exporter

- name: Install and configure smartctl_exporter
  hosts: target_servers
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - smartctl_exporter

- name: Install and configure smokeping_prober
  hosts: target_servers
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - smokeping_prober

- name: Install and configure SNMP exporter
  hosts: target_servers
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - snmp_exporter

- name: Install and configure systemd exporter
  hosts: target_servers
  become: true
  collections:
    - prometheus.prometheus
  roles:
    - systemd_exporter
