#
# Ansible managed
#
# http://prometheus.io/docs/operating/configuration/

global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

  external_labels:
    environment: debian.us-central1-f.c.expriments-427215.internal

rule_files:
  - /etc/prometheus/rules/*.rules

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - debian.us-central1-f.c.expriments-427215.internal:9090

  - job_name: node_exporter
    static_configs:
      - targets:
          - "10.128.0.45:9100"
          - "10.128.0.47:9100"
          - "10.128.0.48:9100"

  - job_name: alertmanager
    static_configs:
      - targets:
          - "10.128.0.45:9093"
          - "10.128.0.47:9093"
          - "10.128.0.48:9093"

  - job_name: bind_exporter
    static_configs:
      - targets:
          - "10.128.0.45:9119"
          - "10.128.0.47:9119"
          - "10.128.0.48:9119"

  - job_name: blackbox_exporter
    static_configs:
      - targets:
          - "10.128.0.45:9115"
          - "10.128.0.47:9115"
          - "10.128.0.48:9115"

  - job_name: cadvisor
    static_configs:
      - targets:
          - "10.128.0.45:8080"
          - "10.128.0.47:8080"
          - "10.128.0.48:8080"

  - job_name: chrony_exporter
    static_configs:
      - targets:
          - "10.128.0.45:9188"
          - "10.128.0.47:9188"
          - "10.128.0.48:9188"

  - job_name: fail2ban_exporter
    static_configs:
      - targets:
          - "10.128.0.45:9191"
          - "10.128.0.47:9191"
          - "10.128.0.48:9191"

  - job_name: ipmi_exporter
    static_configs:
      - targets:
          - "10.128.0.45:9290"
          - "10.128.0.47:9290"
          - "10.128.0.48:9290"

  - job_name: memcached_exporter
    static_configs:
      - targets:
          - "10.128.0.45:9150"
          - "10.128.0.47:9150"
          - "10.128.0.48:9150"

  - job_name: mongodb_exporter
    static_configs:
      - targets:
          - "10.128.0.45:9216"
          - "10.128.0.47:9216"
          - "10.128.0.48:9216"

  - job_name: mysqld_exporter
    static_configs:
      - targets:
          - "10.128.0.45:9104"
          - "10.128.0.47:9104"
          - "10.128.0.48:9104"

  - job_name: nginx_exporter
    static_configs:
      - targets:
          - "10.128.0.45:9113"
          - "10.128.0.47:9113"
          - "10.128.0.48:9113"

  - job_name: postgres_exporter
    static_configs:
      - targets:
          - "10.128.0.45:9187"
          - "10.128.0.47:9187"
          - "10.128.0.48:9187"

  - job_name: process_exporter
    static_configs:
      - targets:
          - "10.128.0.45:9256"
          - "10.128.0.47:9256"
          - "10.128.0.48:9256"

  - job_name: pushgateway
    static_configs:
      - targets:
          - "10.128.0.45:9091"
          - "10.128.0.47:9091"
          - "10.128.0.48:9091"

  - job_name: redis_exporter
    static_configs:
      - targets:
          - "10.128.0.45:9121"
          - "10.128.0.47:9121"
          - "10.128.0.48:9121"

  - job_name: smartctl_exporter
    static_configs:
      - targets:
          - "10.128.0.45:9633"
          - "10.128.0.47:9633"
          - "10.128.0.48:9633"

  - job_name: smokeping_prober
    static_configs:
      - targets:
          - "10.128.0.45:9374"
          - "10.128.0.47:9374"
          - "10.128.0.48:9374"

  - job_name: snmp_exporter
    static_configs:
      - targets:
          - "10.128.0.45:9116"
          - "10.128.0.47:9116"
          - "10.128.0.48:9116"

  - job_name: systemd_exporter
    static_configs:
      - targets:
          - "10.128.0.45:9559"
          - "10.128.0.47:9559"
          - "10.128.0.48:9559"