---
- name: Install Prometheus Exporters
  hosts: target_servers
  become: true
  collections:
    - prometheus.prometheus
  vars_files:
    - vars.yml

  tasks:
    - name: Install and configure Node Exporter
      when: exporters.node_exporter == true
      include_role:
        name: node_exporter

    - name: Install and configure Alert Manager
      when: exporters.alertmanager == true
      include_role:
        name: alertmanager
      vars:
        alertmanager_version: 0.27.0
        alertmanager_receivers:
          - name: discord
            webhook_configs:
              - send_resolved: true
                url: "https://discord.com/api/webhooks/1156904139327017063/UYC-Az12KeFyvpv2nEm_yvo_Ype0yvqenAxJNeNvTLUnN6hH-9p6YBc6jKJOKFWmlUTb"
        alertmanager_route:
          group_by: ['alertname', 'cluster', 'service']
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 3h
          receiver: discord

    - name: Install and configure Bind Exporter
      when: exporters.bind_exporter == true
      include_role:
        name: bind_exporter

    - name: Install and configure Blackbox Exporter
      when: exporters.blackbox_exporter == true
      include_role:
        name: blackbox_exporter

    - name: Install and configure cAdvisor
      when: exporters.cadvisor == true
      include_role:
        name: cadvisor

    - name: Install and configure Chrony Exporter
      when: exporters.chrony_exporter == true
      include_role:
        name: chrony_exporter

    - name: Install and configure Fail2ban Exporter
      when: exporters.fail2ban_exporter == true
      include_role:
        name: fail2ban_exporter

    - name: Install and configure IPMI Exporter
      when: exporters.ipmi_exporter == true
      include_role:
        name: ipmi_exporter

    - name: Install and configure Memcached Exporter
      when: exporters.memcached_exporter == true
      include_role:
        name: memcached_exporter

    - name: Install and configure MongoDB Exporter
      when: exporters.mongodb_exporter == true
      include_role:
        name: mongodb_exporter

    - name: Install and configure MySQL Exporter
      when: exporters.mysqld_exporter == true
      include_role:
        name: mysqld_exporter

    - name: Install and configure NGINX Exporter
      when: exporters.nginx_exporter == true
      include_role:
        name: nginx_exporter

    - name: Install and configure PostgreSQL Exporter
      when: exporters.postgres_exporter == true
      include_role:
        name: postgres_exporter

    - name: Install and configure Process Exporter
      when: exporters.process_exporter == true
      include_role:
        name: process_exporter

    - name: Install and configure Pushgateway
      when: exporters.pushgateway == true
      include_role:
        name: pushgateway

    - name: Install and configure Redis Exporter
      when: exporters.redis_exporter == true
      include_role:
        name: redis_exporter

    - name: Install and configure Smartctl Exporter
      when: exporters.smartctl_exporter == true
      include_role:
        name: smartctl_exporter

    - name: Install and configure Smokeping Prober
      when: exporters.smokeping_prober == true
      include_role:
        name: smokeping_prober

    - name: Install and configure SNMP Exporter
      when: exporters.snmp_exporter == true
      include_role:
        name: snmp_exporter

    - name: Install and configure Systemd Exporter
      when: exporters.systemd_exporter == true
      include_role:
        name: systemd_exporter