---
- name: Run local preparation
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Download nginx_exporter binary to local folder
      become: false
      ansible.builtin.get_url:
        url: "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v{{ nginx_exporter_version }}/\
                nginx-prometheus-exporter_{{ nginx_exporter_version }}_linux_{{ go_arch }}.tar.gz"
        dest: "/tmp/nginx-prometheus-exporter_{{ nginx_exporter_version }}_linux_{{ go_arch }}.tar.gz"
        mode: 0644
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      check_mode: false

    - name: Create local directory for binary
      ansible.builtin.file:
        path: "{{ nginx_exporter_binary_local_dir }}"
        state: directory
        mode: '0755'

    - name: Unpack nginx_exporter binary
      become: false
      ansible.builtin.unarchive:
        src: "/tmp/nginx-prometheus-exporter_{{ nginx_exporter_version }}_linux_{{ go_arch }}.tar.gz"
        dest: "{{ nginx_exporter_binary_local_dir }}"
        creates: "{{ nginx_exporter_binary_local_dir }}/nginx-prometheus-exporter"
      check_mode: false

    - name: Install pyOpenSSL for certificate generation
      ansible.builtin.pip:
        name: "pyOpenSSL"

    - name: Create private key
      community.crypto.openssl_privatekey:
        path: "/tmp/tls.key"

    - name: Create CSR
      community.crypto.openssl_csr:
        path: "/tmp/tls.csr"
        privatekey_path: "/tmp/tls.key"

    - name: Create certificate
      community.crypto.x509_certificate:
        path: "/tmp/tls.cert"
        csr_path: "/tmp/tls.csr"
        privatekey_path: "/tmp/tls.key"
        provider: selfsigned

- name: Run target preparation
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Create nginx_exporter cert dir
      ansible.builtin.file:
        path: "{{ nginx_exporter_tls_server_config.cert_file | dirname }}"
        state: directory
        owner: root
        group: root
        mode: u+rwX,g+rwX,o=rX

    - name: Copy cert and key
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode | default('0644') }}"
      loop:
        - src: "/tmp/tls.cert"
          dest: "{{ nginx_exporter_tls_server_config.cert_file }}"
        - src: "/tmp/tls.key"
          dest: "{{ nginx_exporter_tls_server_config.key_file }}"
