- name: Install and configure Grafana
  hosts: grafana_servers
  become: true
  roles:
    - role: grafana.grafana.grafana
      vars:
        grafana_security:
          admin_user: admin
          admin_password: admin123