---
- name: Install and configure Loki
  hosts: loki_servers
  become: true
  collections:
    - grafana.grafana

  vars:
    loki_version: "latest"  # or a specific version
    loki_http_listen_port: 3100
    loki_http_listen_address: "0.0.0.0"
    loki_storage_config:
      filesystem:
        directory: "/var/lib/loki"
    loki_ruler:
      alertmanager_url: http://localhost:9093

  tasks:
    - name: Install Loki using the Grafana Loki role
      include_role:
        name: grafana.grafana.loki

    - name: Start and enable Loki service
      ansible.builtin.service:
        name: loki
        state: started
        enabled: true