---
- name: Install and configure Grafana
  hosts: grafana_servers
  become: true
  collections:
    - grafana.grafana
  roles:
    - grafana
  vars:
    grafana_security:
      admin_user: admin
      admin_password: adminpaswordp2184d90KHS