---
java_packages:
  Debian: "openjdk-17-jdk"
  RedHat: "java-17-openjdk"

artemis_version: "2.38.0"
artemis_url: "https://downloads.apache.org/activemq/activemq-artemis/{{ artemis_version }}/apache-artemis-{{ artemis_version }}-bin.tar.gz"
artemis_install_dir: "/opt/artemis"
artemis_instance_dir: "/opt/artemis-instance"
artemis_user: "artemis"
artemis_group: "artemis"
artemis_password: "329awfas"

nfs_export_path: "/srv/nfs"
nfs_allowed_hosts: "*"
nfs_service_name:
  RedHat: nfs-server
  Debian: nfs-kernel-server
nfs_server_ip: "34.70.204.185"
nfs_mount_paths:
  master: "/mnt/artemis-cluster-master-prod"
  node1: "/mnt/artemis-cluster-node1-prod"
  node2: "/mnt/artemis-cluster-node2-prod"

connectors:
  master: "tcp://10.7.38.61:61616"
  node1: "tcp://10.1.87.60:61616"
  node2: "tcp://10.7.87.59:61616"