---
- name: Install ActiveMQ Artemis on multiple OS
  hosts: all
  become: yes
  vars:
    java_packages:
      "Ubuntu": "openjdk-11-jdk"
      "Debian": "openjdk-11-jdk"
      "Rocky": "java-11-openjdk"
      "CentOS": "java-11-openjdk"
    artemis_version: "2.37.0"
    artemis_url: "https://downloads.apache.org/activemq/activemq-artemis/{{ artemis_version }}/apache-artemis-{{ artemis_version }}-bin.tar.gz"
    artemis_install_dir: "/opt/artemis"
    artemis_instance_dir: "/opt/artemis-instance"
    artemis_user: "artemis"
    artemis_group: "artemis"
    artemis_password: "329awfas"

  tasks:
    - name: Ensure required packages are installed
      package:
        name:
          - curl
          - wget
          - net-tools
          - git
          - "{{ java_packages[ansible_distribution] }}"
        state: present

    - name: Find Java 11 installation path
      command: "update-alternatives --list java"
      register: java_alternatives_output

    - name: Set default Java version to Java 11
      alternatives:
        name: java
        path: "{{ java_alternatives_output.stdout_lines | select('search', 'java-11') | list | first }}"

    - name: Download ActiveMQ Artemis
      get_url:
        url: "{{ artemis_url }}"
        dest: /tmp/apache-artemis-{{ artemis_version }}-bin.tar.gz

    - name: Extract ActiveMQ Artemis
      unarchive:
        src: /tmp/apache-artemis-{{ artemis_version }}-bin.tar.gz
        dest: /opt
        remote_src: yes

    - name: Move extracted Artemis to installation directory
      command: mv /opt/apache-artemis-{{ artemis_version }} {{ artemis_install_dir }}

    - name: Create artemis group
      group:
        name: "{{ artemis_group }}"
        state: present

    - name: Create artemis user and assign to group
      user:
        name: "{{ artemis_user }}"
        group: "{{ artemis_group }}"
        createhome: yes
        shell: /bin/bash
        state: present

    - name: Change ownership of Artemis directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ artemis_user }}"
        group: "{{ artemis_group }}"
        recurse: yes
      loop:
        - "{{ artemis_install_dir }}"
        - "{{ artemis_instance_dir }}"

    - name: Create Artemis instance
      command: "{{ artemis_install_dir }}/bin/artemis create {{ artemis_instance_dir }} --user admin --password {{ artemis_password }} --allow-anonymous"

    - name: Create systemd service file for Artemis
      copy:
        dest: /etc/systemd/system/artemis.service
        content: |
          [Unit]
          Description=ActiveMQ Artemis Service
          After=network.target

          [Service]
          Type=forking
          ExecStart={{ artemis_instance_dir }}/bin/artemis-service start
          ExecStop={{ artemis_instance_dir }}/bin/artemis-service stop
          User={{ artemis_user }}
          Group={{ artemis_group }}
          Restart=on-abort

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable and start the Artemis service
      systemd:
        name: artemis
        enabled: yes
        state: started

    - name: Update bootstrap.xml to bind to 0.0.0.0
      replace:
        path: "{{ artemis_instance_dir }}/etc/bootstrap.xml"
        regexp: '(<binding name="artemis" uri="http://)(.*)(:8161">)'
        replace: '\1{{ ansible_default_ipv4.address }}\3'

    - name: Update Jolokia access to allow cross-origin requests
      replace:
        path: "{{ artemis_instance_dir }}/etc/jolokia-access.xml"
        regexp: '<allow-origin>.*</allow-origin>'
        replace: '<allow-origin>*://*</allow-origin>'

    - name: Ensure Jolokia CORS settings are permissive
      replace:
        path: "{{ artemis_instance_dir }}/etc/jolokia-access.xml"
        regexp: '<strict-checking/>'
        replace: ''
