FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ansible \
    openssh-client \
    sshpass \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ .

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]