---
provisioner:
  inventory:
    group_vars:
      all:
        postgres_exporter_binary_local_dir: "/tmp/postgres_exporter-linux-amd64"
        postgres_exporter_web_listen_address:
          - '127.0.0.1:8080'
          - '127.0.1.1:8080'
        postgres_exporter_enabled_collectors:
          - postmaster
        postgres_exporter_disabled_collectors:
          - replication

        postgres_exporter_tls_server_config:
          cert_file: /etc/postgres_exporter/tls.cert
          key_file: /etc/postgres_exporter/tls.key
        postgres_exporter_http_server_config:
          http2: true
        postgres_exporter_basic_auth_users:
          randomuser: examplepassword
        go_arch: amd64
        postgres_exporter_version: 0.15.0
