- name: Deploy Ceph Cluster
  hosts: all
  become: true
  vars:
    ceph_dashboard_admin_user: "admin"
    ceph_dashboard_admin_password: "erlg@2483LFJEqfdm"
    cephadm_bootstrap_host: "{{ groups['mons'][0] }}"

  tasks:
    - name: Bootstrap the Ceph cluster
      include_role:
        name: stackhpc.cephadm.cephadm
      vars:
        ceph_version: "quincy"
        cephadm_enable_dashboard: true
        cephadm_enable_monitoring: true
        cephadm_install_ceph_cli: true
        cephadm_public_interface: "eth0"
        cephadm_cluster_interface: "eth1"
        cephadm_public_network: "0.0.0.0/0"
        cephadm_cluster_network: "10.116.0.0/20"
        ceph_osd_devices:
          - /dev/sda
          - /dev/sdb
          - /dev/sdc

    - name: Wait for Ceph cluster to be ready
      command: ceph -s
      register: ceph_status
      retries: 10
      delay: 30
      until: ceph_status.rc == 0
      delegate_to: "{{ cephadm_bootstrap_host }}"

    - name: Create a temporary password file
      copy:
        content: "{{ ceph_dashboard_admin_password }}"
        dest: /tmp/admin_password
        mode: 0600
      delegate_to: "{{ cephadm_bootstrap_host }}"

    - name: Set Ceph dashboard admin user and password
      command: >
        ceph dashboard ac-user-create {{ ceph_dashboard_admin_user }} -i /tmp/admin_password administrator
      delegate_to: "{{ cephadm_bootstrap_host }}"

    - name: Ensure password update is not required on first login
      command: ceph dashboard ac-user-set-password {{ ceph_dashboard_admin_user }} -i /tmp/admin_password --force-password
      delegate_to: "{{ cephadm_bootstrap_host }}"

    - name: Clean up temporary password file
      file:
        path: /tmp/admin_password
        state: absent
      delegate_to: "{{ cephadm_bootstrap_host }}"


# - name: Configure CRUSH Rules
#   hosts: all
#   tasks:
#     - name: Define CRUSH rules for HDD and SSD
#       include_role:
#         name: stackhpc.cephadm.crush_rules
#       vars:
#         cephadm_crush_rules:
#           - name: replicated_hdd
#             bucket_root: default
#             bucket_type: host
#             device_class: hdd
#             rule_type: replicated
#             state: present
#           - name: replicated_ssd
#             bucket_root: default
#             bucket_type: host
#             device_class: ssd
#             rule_type: replicated
#             state: present

# - name: Configure Ceph Pools
#   hosts: all
#   tasks:
#     - name: Define Ceph pools for various applications
#       include_role:
#         name: stackhpc.cephadm.pools
#       vars:
#         cephadm_pools:
#           - name: backups
#             application: rbd
#             state: present
#           - name: images
#             application: rbd
#             state: present
#           - name: volumes
#             application: rbd
#             state: present
#           - name: vms
#             application: rbd
#             state: present