---
- name: Install Certbot and NGINX plugin on multiple OSes
  hosts: certbot_servers
  become: yes
  tasks:
    - name: Install Certbot and NGINX plugin on Debian/Ubuntu
      apt:
        name:
          - certbot
          - python3-certbot-nginx
        state: present
      when: ansible_facts['os_family'] == "Debian"
    
    - name: Install Certbot and NGINX plugin on CentOS/RHEL/Rocky
      dnf:
        name:
          - certbot
          - python3-certbot-nginx
        state: present
      when: ansible_facts['os_family'] == "RedHat"