---
- hosts: activemq_servers
  become: true
  gather_facts: true
  vars_files:
    - vars/vars.yml
  collections:
    - middleware_automation.amq
  roles:
    - role: activemq
      vars:
        activemq_tls_enabled: false
        activemq_shared_storage: false
        activemq_queues:
          - "queue.in"
          - "queue.out"
        activemq_users:
          - user: "{{ activemq_instance_username }}"
            password: "{{ activemq_instance_password }}"
            roles: [ "admin" ]
        activemq_roles:
          - name: "admin"
            permissions: [ "createNonDurableQueue", "deleteNonDurableQueue", "manage" ]