---
- name: Configure PostgreSQL
  hosts: all
  become: yes
  vars_files:
  - vars.yml
  tasks:
    - name: Update listen_addresses in postgresql.conf
      ansible.builtin.lineinfile:
        path: "{{ postgresql_conf_path }}"
        regexp: "^#?listen_addresses\\s*=\\s*.*"
        line: "listen_addresses = '*'"
      notify: Restart PostgreSQL

    - name: Add IPv4 entry to pg_hba.conf
      ansible.builtin.lineinfile:
        path: "{{ pg_hba_conf_path }}"
        line: "host    all             all             0.0.0.0/0               md5"
        state: present
      notify: Restart PostgreSQL

    - name: Add IPv6 entry to pg_hba.conf
      ansible.builtin.lineinfile:
        path: "{{ pg_hba_conf_path }}"
        line: "host    all             all             ::/0                    md5"
        state: present
      notify: Restart PostgreSQL

  handlers:
    - name: Restart PostgreSQL
      ansible.builtin.service:
        name: "{{ postgresql_service_name }}"
        state: restarted