---
- name: Install and configure PostgreSQL
  hosts: postgresql_servers
  become: true
  vars:
    postgresql_version: 16
    postgresql_listen_addresses: "*"
    postgresql_pg_hba_conf:
      - { type: host, database: all, user: all, address: '0.0.0.0/0', method: md5 }
    postgresql_password: "123"

  roles:
    - galaxyproject.postgresql

  tasks:
    - name: Set PostgreSQL user password
      become_user: postgres
      postgresql_user:
        name: postgres
        password: "{{ postgresql_password }}"

# ansible-galaxy install galaxyproject.postgresql