---
- name: Install PostgreSQL
  hosts: postgresql_servers
  become: true
  vars:
    postgresql_version: 16

  roles:
    - galaxyproject.postgresql

  tasks:
    - name: Install PostgreSQL package
      ansible.builtin.package:
        name: "postgresql-{{ postgresql_version }}"
        state: present

    - name: Initialize PostgreSQL if not initialized
      ansible.builtin.shell: postgresql-setup --initdb
      when: not postgresql_is_initialized.stat.exists

    - name: Start and enable PostgreSQL service
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true