---
- name: Setup PostgreSQL users and roles
  hosts: postgresql_servers
  become: true
  vars:
    postgres_users:
      - { name: 'admin_user', password: 'AdminPassword123', role_attr_flags: 'CREATEDB,CREATEROLE' }
      - { name: 'readonly_user', password: 'ReadOnlyPass', role_attr_flags: 'NOSUPERUSER,NOCREATEDB,NOCREATEROLE' }
    postgres_databases:
      - { name: 'mydatabase', owner: 'admin_user' }

  tasks:
    - name: Ensure PostgreSQL is running
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true

    - name: Create PostgreSQL users
      become_user: postgres
      postgresql_user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        role_attr_flags: "{{ item.role_attr_flags }}"
      with_items: "{{ postgres_users }}"
      notify: Restart PostgreSQL

    - name: Create PostgreSQL databases
      become_user: postgres
      postgresql_db:
        name: "{{ item.name }}"
        owner: "{{ item.owner }}"
      with_items: "{{ postgres_databases }}"
      notify: Restart PostgreSQL

  handlers:
    - name: Restart PostgreSQL
      ansible.builtin.service:
        name: postgresql
        state: restarted