---
- name: Configure Cassandra for external access and authentication
  hosts: cassandra_nodes
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Ensure Cassandra is configured to listen on 0.0.0.0
      lineinfile:
        path: /etc/cassandra/cassandra.yaml
        regexp: '^(listen_address|rpc_address|broadcast_address):.*'
        line: "{{ item }}"
        state: present
      loop:
        - "listen_address: 0.0.0.0"
        - "rpc_address: 0.0.0.0"
        - "broadcast_address: {{ broadcast_address }}"

    - name: Enable Cassandra authentication and authorization
      lineinfile:
        path: /etc/cassandra/cassandra.yaml
        regexp: '^(authenticator|authorizer):.*'
        line: "{{ item }}"
        state: present
      loop:
        - "authenticator: PasswordAuthenticator"
        - "authorizer: CassandraAuthorizer"

    - name: Restart Cassandra to apply configuration
      service:
        name: cassandra
        state: restarted

    - name: Set password for Cassandra user and enable external access
      community.cassandra.cassandra_role:
        name: "{{ cassandra_user }}"
        password: "{{ cassandra_password }}"
        super_user: yes
        state: present
        login_host: "{{ ansible_host }}"
        login_password: "{{ cassandra_password }}"

    - name: Open firewall for external access to Cassandra ports
      firewalld:
        port: "{{ item }}/tcp"
        permanent: yes
        state: enabled
      loop:
        - 9042  # CQL native transport port
        - 7000  # Internode communication
        - 7001  # SSL internode communication
        - 7199  # JMX monitoring port

    - name: Reload firewall to apply changes
      firewalld:
        immediate: yes
        permanent: yes
        state: reloaded