---
- hosts: php_servers
  become: yes
  vars:
    php_version: "8.3"  # Specify the PHP version you want to install
  roles:
    - name: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - geerlingguy.php-versions
    - geerlingguy.php