---
- name: Install kubectl for x86_64 or arm64 architecture
  hosts: all
  become: yes
  vars:
    kubectl_architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"
    
  tasks:
    - name: Download kubectl binary
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/{{ lookup('url', 'https://dl.k8s.io/release/stable.txt') }}/bin/linux/{{ kubectl_architecture }}/kubectl"
        dest: /tmp/kubectl
        mode: '0755'

    - name: Download kubectl sha256 file
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/{{ lookup('url', 'https://dl.k8s.io/release/stable.txt') }}/bin/linux/{{ kubectl_architecture }}/kubectl.sha256"
        dest: /tmp/kubectl.sha256

    - name: Verify kubectl sha256 checksum
      ansible.builtin.shell: |
        echo "$(cat /tmp/kubectl.sha256)  /tmp/kubectl" | sha256sum --check
      register: sha256_check
      failed_when: "'OK' not in sha256_check.stdout"

    - name: Install kubectl
      ansible.builtin.command:
        cmd: "install -o root -g root -m 0755 /tmp/kubectl /usr/local/bin/kubectl"

    - name: Check kubectl version
      ansible.builtin.command:
        cmd: kubectl version --client
      register: kubectl_version

    - name: Show kubectl version
      debug:
        var: kubectl_version.stdout
