- name: Install and configure Java 17 on multiple OS families
  hosts: all
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Install Java 17 on Debian-based systems
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Java 17 on RedHat-based systems
      ansible.builtin.yum:
        name: java-17-openjdk
        state: present
      when: ansible_os_family == "RedHat"

    - name: Identify Java 17 path on Debian-based systems
      ansible.builtin.shell: "update-alternatives --list java | grep 'java-17'"
      register: debian_java_path
      when: ansible_os_family == "Debian"

    - name: Identify Java 17 path on RedHat-based systems
      ansible.builtin.shell: "update-alternatives --list | grep 'java-17'"
      register: redhat_java_path
      when: ansible_os_family == "RedHat"

    - name: Set Java 17 as the default alternative on Debian-based systems
      community.general.alternatives:
        name: java
        path: "{{ debian_java_path.stdout }}"
        priority: 100
      when: ansible_os_family == "Debian"

    - name: Set Java 17 as the default alternative on RedHat-based systems
      community.general.alternatives:
        name: java
        path: "{{ redhat_java_path.stdout }}"
        priority: 100
      when: ansible_os_family == "RedHat"

    - name: Verify Java 17 installation
      ansible.builtin.command: java -version
      register: java_version

    - name: Display Java version
      ansible.builtin.debug:
        msg: "Java installed successfully. Version: {{ java_version.stdout_lines }}"