---
- name: Configure Redis
  hosts: redis_servers
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: Disable protected mode
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^protected-mode'
        line: "protected-mode {{ redis_protected_mode }}"
        state: present
      notify: Restart Redis

    - name: Set bind address to 0.0.0.0
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^bind'
        line: "bind {{ redis_bind_interface }}"
        state: present
      notify: Restart Redis

  handlers:
    - name: Restart Redis
      service:
        name: "{{ ansible_os_family == 'RedHat' | ternary('redis', 'redis-server') }}"
        state: restarted