---
- name: Configure Redis
  hosts: redis_servers
  become: yes
  vars:
    redis_protected_mode: "no"
    redis_bind: "0.0.0.0"
    debian_redis_package: "redis-server"
    redhat_redis_package: "redis"
  tasks:
    - name: Modify 'protected-mode' in redis.conf
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^protected-mode'
        line: "protected-mode {{ redis_protected_mode }}"
        state: present
        backrefs: yes

    - name: Modify 'bind' in redis.conf
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: '^bind'
        line: "bind {{ redis_bind }}"
        state: present
        backrefs: yes

    - name: Restart Redis service on Debian-based systems
      service:
        name: "{{ debian_redis_package }}"
        state: restarted
      when: ansible_os_family == "Debian"

    - name: Restart Redis service on RedHat-based systems
      service:
        name: "{{ redhat_redis_package }}"
        state: restarted
      when: ansible_os_family == "RedHat"