---
- name: Update and upgrade multiple OS
  hosts: all
  become: true
  tasks:
    - name: Gather OS facts
      ansible.builtin.setup:
        filter: ansible_os_family

    - name: Update and upgrade Debian-based systems (Ubuntu, Debian)
      block:
        - name: Update package list
          ansible.builtin.apt:
            update_cache: yes
            cache_valid_time: 3600

        - name: Upgrade packages
          ansible.builtin.apt:
            upgrade: dist
      when: ansible_os_family == 'Debian'

    - name: Install GPG key and EPEL repo on RedHat-based systems (RedHat, CentOS, Rocky)
      block:
        - name: Install GPG key for EPEL
          ansible.builtin.rpm_key:
            state: present
            key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        
        - name: Download and install EPEL repository RPM
          ansible.builtin.get_url:
            url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
            dest: "/tmp/epel-release.rpm"
        
        - name: Install EPEL repository
          ansible.builtin.dnf:
            name: "/tmp/epel-release.rpm"
            state: present
      when: ansible_os_family == 'RedHat'

    - name: Update and upgrade RedHat-based systems (RedHat, CentOS, Rocky)
      block:
        - name: Update package list
          ansible.builtin.dnf:
            update_cache: yes

        - name: Upgrade packages
          ansible.builtin.dnf:
            name: "*"
            state: latest
      when: ansible_os_family == 'RedHat'

    - name: Update and upgrade SUSE-based systems
      block:
        - name: Refresh package list
          ansible.builtin.zypper:
            update_cache: yes

        - name: Upgrade packages
          ansible.builtin.zypper:
            name: "*"
            state: latest
      when: ansible_os_family == 'Suse'

    - name: Install required tools on Debian-based systems
      block:
        - name: Install common tools
          ansible.builtin.apt:
            name:
              - git
              - curl
              - wget
              - vim
              - htop
              - nano
              - net-tools
              - traceroute
            state: present
      when: ansible_os_family == 'Debian'

    - name: Install required tools on RedHat-based systems
      block:
        - name: Install common tools
          ansible.builtin.dnf:
            name:
              - git
              - curl
              - wget
              - vim
              - htop
              - nano
              - net-tools
              - traceroute
            state: present
      when: ansible_os_family == 'RedHat'

    - name: Install required tools on SUSE-based systems
      block:
        - name: Install common tools
          ansible.builtin.zypper:
            name:
              - git
              - curl
              - wget
              - vim
              - htop
              - nano
              - net-tools
              - traceroute
            state: present
      when: ansible_os_family == 'Suse'