---
# RabbitMQ Docker

rabbitmq_image: "4.0-management"
container_name: "rabbitmq"
host_port: 5672
management_port: 15672
admin_user: "admin"
admin_password: "oh234lrfw($)"
host_path: "/mnt/rabbitmq_data"