---
- name: Create the process_exporter group
  ansible.builtin.group:
    name: "{{ process_exporter_system_group }}"
    state: present
    system: true
  when: process_exporter_system_group != "root"

- name: Create the process_exporter user
  ansible.builtin.user:
    name: "{{ process_exporter_system_user }}"
    groups: "{{ process_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: process_exporter_system_user != "root"

- name: Get binary
  when:
    - process_exporter_binary_local_dir | length == 0
    - not process_exporter_skip_install
  block:

    - name: Download process_exporter binary to local folder
      become: false
      ansible.builtin.get_url:
        url: "{{ process_exporter_binary_url }}"
        dest: "{{ process_exporter_archive_path }}/process_exporter-{{ process_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        checksum: "sha256:{{ __process_exporter_checksum }}"
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack process_exporter binary
      become: false
      ansible.builtin.unarchive:
        src: "{{ process_exporter_archive_path }}/process_exporter-{{ process_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "{{ process_exporter_archive_path }}"
        creates: "{{ process_exporter_archive_path }}/process-exporter-{{ process_exporter_version }}.linux-{{ go_arch }}/process-exporter"
      delegate_to: localhost
      check_mode: false

    - name: Propagate process_exporter binaries
      ansible.builtin.copy:
        src: "{{ process_exporter_archive_path }}/process-exporter-{{ process_exporter_version }}.linux-{{ go_arch }}/process-exporter"
        dest: "{{ process_exporter_binary_install_dir }}/process_exporter"
        mode: 0755
        owner: root
        group: root
      notify: restart process_exporter
      when: not ansible_check_mode

- name: Propagate locally distributed process_exporter binary
  ansible.builtin.copy:
    src: "{{ process_exporter_binary_local_dir }}/process-exporter"
    dest: "{{ process_exporter_binary_install_dir }}/process_exporter"
    mode: 0755
    owner: root
    group: root
  when:
    - process_exporter_binary_local_dir | length > 0
    - not process_exporter_skip_install
  notify: restart process_exporter
