---
- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
    apply:
      tags:
        - process_exporter_install
        - process_exporter_configure
        - process_exporter_run
  tags:
    - process_exporter_install
    - process_exporter_configure
    - process_exporter_run

- name: Install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true
      tags:
        - process_exporter_install
  tags:
    - process_exporter_install

- name: SELinux
  ansible.builtin.include_tasks:
    file: selinux.yml
    apply:
      become: true
      tags:
        - process_exporter_configure
  when: ansible_selinux.status == "enabled"
  tags:
    - process_exporter_configure

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: true
      tags:
        - process_exporter_configure
  tags:
    - process_exporter_configure

- name: Ensure process_exporter is enabled on boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: process_exporter
    enabled: true
    state: started
  when:
    - not ansible_check_mode
  tags:
    - process_exporter_run
