---
provisioner:
  inventory:
    group_vars:
      all:
        process_exporter_binary_local_dir: "/tmp/process_exporter-linux-amd64"
        process_exporter_web_listen_address: "127.0.0.1:8080"
        process_exporter_tls_server_config:
          cert_file: /etc/process_exporter/tls.cert
          key_file: /etc/process_exporter/tls.key
        process_exporter_http_server_config:
          http2: true
        process_exporter_basic_auth_users:
          randomuser: examplepassword
        go_arch: amd64
        process_exporter_version: 0.7.10
        process_exporter_names: |
          {% raw %}
            - name: "{{.Comm}}"
              cmdline:
                - systemd
            - name: "{{.Comm}}"
              cmdline:
                - systemd-journald
            - name: "{{.Comm}}"
              cmdline:
                - crond
          {% endraw %}
