---
- name: Install Cert-Manager
  hosts: all
  become: yes
  vars:
    version: "v1.15.3"  # Cert-manager version
    namespace: "cert-manager"  # Cert-manager namespace

  tasks:
    - name: Apply cert-manager CRDs
      ansible.builtin.command:
        cmd: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/{{ version }}/cert-manager.crds.yaml

    - name: Add Jetstack Helm repo
      ansible.builtin.command:
        cmd: helm repo add jetstack https://charts.jetstack.io

    - name: Update Helm repo
      ansible.builtin.command:
        cmd: helm repo update

    - name: Install cert-manager using Helm
      ansible.builtin.command:
        cmd: helm install cert-manager jetstack/cert-manager --namespace {{ namespace }} --create-namespace --version {{ version }}
      register: helm_install_output

    - name: Wait for 1 minute to let Cert-Manager pods start
      ansible.builtin.pause:
        minutes: 1

    - name: Get all Cert-Manager resources
      ansible.builtin.command:
        cmd: kubectl get all -n {{ namespace }}
      register: cert_manager_resources

    - name: Show Cert-Manager resources
      debug:
        var: cert_manager_resources.stdout