---
- name: Configure Nexus Repository OSS
  hosts: nexus_servers
  become: true

  vars:
    nexus_privileges:
      - name: all-repos-read
        description: 'Read & Browse access to all repos'
        repository: '*'
        actions:
          - read
          - browse
      - name: company-project-deploy
        description: 'Deployments to company-project'
        repository: company-project
        actions:
          - add
          - edit

    nexus_roles:
      - id: Developpers
        name: developers
        description: All developers
        privileges:
          - nx-search-read
          - all-repos-read
          - company-project-deploy
        roles: []

    nexus_local_users:
      - username: jenkins
        first_name: Jenkins
        last_name: CI
        email: support@company.com
        password: "s3cr3t"
        roles:
          - Developpers

    nexus_blobstores:
      - name: company-artifacts
        path: /var/nexus/blobs/company-artifacts

    nexus_scheduled_tasks:
      - name: compact-blobstore
        cron: '0 0 22 * * ?'
        typeId: blobstore.compact
        taskProperties:
          blobstoreName: 'company-artifacts'

    # Maven Repositories
    nexus_repos_maven_proxy:
      - name: central
        remote_url: 'https://repo1.maven.org/maven2/'
        layout_policy: permissive
    nexus_repos_maven_hosted:
      - name: company-project
        version_policy: mixed
        write_policy: allow
        blob_store: company-artifacts
    nexus_repos_maven_group:
      - name: public
        member_repos:
          - central
          - company-project

    # NPM Repositories
    nexus_repos_npm_proxy:
      - name: npm-proxy
        blob_store: company-artifacts
        remote_url: 'https://registry.npmjs.org/'
      - name: npm-hosted
        blob_store: company-artifacts
        version_policy: mixed
        write_policy: allow
    nexus_repos_npm_group:
      - name: npm-all
        member_repos:
          - npm-hosted
          - npm-proxy

    # Pypi Repositories
    nexus_repos_pypi_proxy:
      - name: pypi-proxy
        remote_url: 'https://pypi.org/simple'
        blob_store: company-artifacts
    nexus_repos_pypi_hosted:
      - name: pypi-hosted
        blob_store: company-artifacts
        write_policy: allow
    nexus_repos_pypi_group:
      - name: pypi-all
        member_repos:
          - pypi-hosted
          - pypi-proxy

    # APT Repositories
    nexus_repos_apt_hosted:
      - name: apt-hosted
        blob_store: company-artifacts
        write_policy: allow
        distribution: 'bionic'
        component: 'main'
    nexus_repos_apt_proxy:
      - name: apt-proxy
        remote_url: 'http://archive.ubuntu.com/ubuntu'
        blob_store: company-artifacts
        distribution: 'bionic'
        component: 'main'
    nexus_repos_apt_group:
      - name: apt-all
        member_repos:
          - apt-hosted
          - apt-proxy

    # RPM/Yum Repositories
    nexus_repos_yum_hosted:
      - name: yum-hosted
        blob_store: company-artifacts
        write_policy: allow
        yum_repodata_depth: 2
    nexus_repos_yum_proxy:
      - name: yum-proxy
        remote_url: 'http://mirror.centos.org/centos/'
        blob_store: company-artifacts
        yum_repodata_depth: 2
    nexus_repos_yum_group:
      - name: yum-all
        member_repos:
          - yum-hosted
          - yum-proxy

    # Docker Repositories
    nexus_repos_docker_group:
      - name: docker-group
        sub_domain: hub-proxy
        writable_member_repo: docker-hosted-repo
        blob_store: docker-blob
        v1_enabled: False
        member_repos:
          - docker-hosted-repo

    # Helm Repositories
    nexus_repos_helm_hosted:
      - name: helm-hosted
        blob_store: company-artifacts
        write_policy: allow
    nexus_repos_helm_proxy:
      - name: helm-proxy
        remote_url: 'https://charts.helm.sh/stable'
        blob_store: company-artifacts
    nexus_repos_helm_group:
      - name: helm-all
        member_repos:
          - helm-hosted
          - helm-proxy

    # Git LFS Repositories
    nexus_repos_gitlfs_hosted:
      - name: git-lfs
        blob_store: company-artifacts
        write_policy: allow

  tasks:
    - name: Apply Nexus Configuration
      include_role:
        name: ansible-ThoTeam.nexus3-oss
      vars:
        nexus_privileges: "{{ nexus_privileges }}"
        nexus_roles: "{{ nexus_roles }}"
        nexus_local_users: "{{ nexus_local_users }}"
        nexus_blobstores: "{{ nexus_blobstores }}"
        nexus_scheduled_tasks: "{{ nexus_scheduled_tasks }}"
        nexus_repos_maven_proxy: "{{ nexus_repos_maven_proxy }}"
        nexus_repos_maven_hosted: "{{ nexus_repos_maven_hosted }}"
        nexus_repos_maven_group: "{{ nexus_repos_maven_group }}"
        nexus_repos_npm_proxy: "{{ nexus_repos_npm_proxy }}"
        nexus_repos_npm_group: "{{ nexus_repos_npm_group }}"
        nexus_repos_pypi_proxy: "{{ nexus_repos_pypi_proxy }}"
        nexus_repos_pypi_hosted: "{{ nexus_repos_pypi_hosted }}"
        nexus_repos_pypi_group: "{{ nexus_repos_pypi_group }}"
        nexus_repos_apt_hosted: "{{ nexus_repos_apt_hosted }}"
        nexus_repos_apt_proxy: "{{ nexus_repos_apt_proxy }}"
        nexus_repos_apt_group: "{{ nexus_repos_apt_group }}"
        nexus_repos_yum_hosted: "{{ nexus_repos_yum_hosted }}"
        nexus_repos_yum_proxy: "{{ nexus_repos_yum_proxy }}"
        nexus_repos_yum_group: "{{ nexus_repos_yum_group }}"
        nexus_repos_docker_group: "{{ nexus_repos_docker_group }}"
        nexus_repos_helm_hosted: "{{ nexus_repos_helm_hosted }}"
        nexus_repos_helm_proxy: "{{ nexus_repos_helm_proxy }}"
        nexus_repos_helm_group: "{{ nexus_repos_helm_group }}"
        nexus_repos_gitlfs_hosted: "{{ nexus_repos_gitlfs_hosted }}"

    - name: Verify Nexus Configuration
      uri:
        url: "http://localhost:8081"
        return_content: true
      register: nexus_status

    - debug:
        msg: "Nexus configuration applied successfully!"
      when: nexus_status.status == 200