---
- name: Install and configure Nexus Repository OSS
  hosts: nexus_servers
  become: true
  vars:
    # Specify the Nexus version to install
    nexus_version: "3.69.0"

    # Nexus installation directories
    nexus_installation_dir: "/opt/nexus"
    nexus_data_dir: "/var/nexus/data"

    # Nexus ports and host configuration
    nexus_default_port: 8081
    nexus_application_host: "0.0.0.0"

    # Nexus OS user and group
    nexus_os_user: "nexus"
    nexus_os_group: "nexus"
    nexus_os_uid: 1001
    nexus_os_gid: 1001

    # JVM settings for Nexus
    nexus_min_heap_size: "1200M"
    nexus_max_heap_size: "1200M"
    nexus_max_direct_memory: "2G"

    # Define a custom blobstore
    nexus_blobstores:
      - name: "custom-blobstore"
        path: "/mnt/blobstores/custom"

    # Define a scheduled task to compact blobstore every day at midnight
    nexus_scheduled_tasks:
      - name: "compact-blobstore"
        cron: "0 0 * * *"
        typeId: "blobstore.compact"
        taskProperties:
          blobstoreName: "custom-blobstore"

    # Define local users to create in Nexus
    nexus_local_users:
      - username: "admin"
        first_name: "Admin"
        last_name: "User"
        email: "admin@example.com"
        password: "AdminPassword123"
        roles:
          - nx-admin

  roles:
    - role: ansible-ThoTeam.nexus3-oss

  tasks:
    - name: Ensure Nexus service is started
      systemd:
        name: nexus
        state: started
        enabled: true

    - name: Open firewall for Nexus port 8081
      firewalld:
        service: nexus
        port: 8081/tcp
        permanent: true
        state: enabled
      when: ansible_os_family == "RedHat"

    - name: Check if Nexus is running
      uri:
        url: "http://localhost:{{ nexus_default_port }}"
        return_content: true
      register: nexus_status

    - debug:
        msg: "Nexus is up and running!" 
      when: nexus_status.status == 200