---
- name: Install necessary tools (rsync and Java)
  hosts: nexus_servers
  become: true

  tasks:
    - name: Install rsync on Debian-based systems
      apt:
        name: rsync
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install rsync on RHEL-based systems
      yum:
        name: rsync
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install Java on RHEL-based systems
      include_role:
        name: geerlingguy.java
      vars:
        java_packages:
          - java-11-openjdk
          - java-11-openjdk-devel
      when: ansible_os_family == 'RedHat'

    - name: Install Java on Debian-based systems
      include_role:
        name: geerlingguy.java
      vars:
        java_packages:
          - openjdk-17-jdk
          - default-jdk
          - default-jre
      when: ansible_os_family == 'Debian'

    - name: Install Java on Ubuntu systems
      include_role:
        name: geerlingguy.java
      vars:
        java_packages:
          - openjdk-11-jdk
      when: ansible_distribution == 'Ubuntu'