---
- name: Install Docker on multiple OS
  hosts: all
  become: true
  tasks:
    - name: Gather facts
      ansible.builtin.setup:
        filter: ansible_distribution*

    - name: Show system distribution
      debug:
        msg: "Installing Docker on {{ ansible_distribution }}"

    - name: Remove old Docker versions (Debian/Ubuntu based)
      ansible.builtin.package:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - docker-compose-v2
          - podman-docker
          - containerd
          - runc
        state: absent
      when: ansible_distribution in ['Ubuntu', 'Debian']
      tags: debian_ubuntu

    - name: Remove old Docker versions (RHEL/CentOS/Rocky/Fedora based)
      ansible.builtin.shell: |
        sudo {{ ansible_pkg_mgr }} remove -y docker \
                                        docker-client \
                                        docker-client-latest \
                                        docker-common \
                                        docker-latest \
                                        docker-latest-logrotate \
                                        docker-logrotate \
                                        docker-engine
      when: ansible_distribution in ['CentOS', 'RedHat', 'Fedora', 'Rocky']
      tags: rhel_centos_rocky

    - name: Install Docker on Debian/Ubuntu based systems
      block:
        - name: Install dependencies
          ansible.builtin.apt:
            name: "{{ item }}"
            state: present
          loop:
            - ca-certificates
            - curl
            - gnupg

        - name: Add Docker’s official GPG key
          ansible.builtin.shell: |
            install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg -o /etc/apt/keyrings/docker.asc
            chmod a+r /etc/apt/keyrings/docker.asc

        - name: Add Docker APT repository
          ansible.builtin.shell: |
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list
            apt-get update

        - name: Install Docker
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            state: present
      when: ansible_distribution in ['Ubuntu', 'Debian']
      tags: debian_ubuntu

    - name: Install Docker on CentOS/RHEL/Rocky based systems
      block:
        - name: Install dependencies
          ansible.builtin.yum:
            name: yum-utils
            state: present

        - name: Add Docker repository
          ansible.builtin.shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

        - name: Install Docker
          ansible.builtin.yum:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            state: present
      when: ansible_distribution in ['RedHat', 'CentOS', 'Rocky']
      tags: rhel_centos_rocky

    - name: Install Docker on Fedora based systems
      block:
        - name: Install dnf-plugins-core
          ansible.builtin.dnf:
            name: dnf-plugins-core
            state: present

        - name: Add Docker repository
          ansible.builtin.shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

        - name: Install Docker
          ansible.builtin.dnf:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            state: present
      when: ansible_distribution == 'Fedora'
      tags: fedora

    - name: Start and enable Docker
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Set permissions on Docker socket
      ansible.builtin.file:
        path: /var/run/docker.sock
        owner: "{{ ansible_user_id }}"
        group: docker
        mode: '0666'

    - name: Print Docker version
      ansible.builtin.shell: docker --version
      register: docker_version_output

    - name: Show Docker version
      debug:
        msg: "Installed Docker version: {{ docker_version_output.stdout }}"
