---
- name: Install MongoDB
  hosts: mongodb_servers
  become: true
  vars:
    mongodb_version: "7.0"
  collections:
    - community.mongodb
  roles:
      - mongodb_repository
      - mongodb_install

  tasks:
    - name: Start MongoDB service
      ansible.builtin.systemd:
        name: mongod
        state: started
        enabled: true

    - name: Wait for MongoDB service to be up
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: 27017
        state: started