---
- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
    apply:
      tags:
        - snmp_exporter_install
        - snmp_exporter_configure
        - snmp_exporter_run
  tags:
    - snmp_exporter_install
    - snmp_exporter_configure
    - snmp_exporter_run

- name: Install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true
      tags:
        - snmp_exporter_install
  tags:
    - snmp_exporter_install

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: true
      tags:
        - snmp_exporter_configure
  tags:
    - snmp_exporter_configure

- name: Ensure snmp_exporter service is started and enabled
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: snmp_exporter
    state: started
    enabled: true
  tags:
    - snmp_exporter_run
