---
- name: Restart snmp_exporter
  listen: "restart snmp_exporter"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: snmp_exporter
    state: restarted
  register: snmp_exporter_restarted

- name: Reload snmp_exporter
  listen: "reload snmp_exporter"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: snmp_exporter
    state: reloaded
  when: snmp_exporter_restarted is not defined
