name: Code Checkout

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            repository: ismoilovdevml/infra-as-code
            path: infra-as-code