---
- name: Configure MySQL and grant root access
  hosts: mysql_servers
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Ensure MySQL is listening on all interfaces (Debian/Ubuntu/MariaDB)
      lineinfile:
        path: /etc/mysql/my.cnf
        regexp: '^bind-address'
        line: 'bind-address = {{ bind-address }}'
        state: present
      when: ansible_os_family == "Debian"
      notify: Restart MySQL

    - name: Ensure MySQL is listening on all interfaces (RHEL/CentOS)
      lineinfile:
        path: /etc/my.cnf
        regexp: '^bind-address'
        line: 'bind-address = {{ bind-address }}'
        state: present
      when: ansible_os_family == "RedHat"
      notify: Restart MySQL

    - name: Grant root access from any host
      mysql_user:
        name: root
        host: '%'
        password: "{{ mysql_root_password }}"
        priv: '*.*:ALL,GRANT'
        state: present

    - name: Flush privileges to apply changes
      mysql_query:
        query: "FLUSH PRIVILEGES;"
        login_user: root
        login_password: "{{ mysql_root_password }}"
      ignore_errors: yes

  handlers:
    - name: Restart MySQL
      service:
        name: mysql
        state: restarted
