---
- name: Install and configure MySQL
  hosts: mysql_servers
  become: yes

  vars:
    mysql_root_password: "123"
    mysql_bind_address: '0.0.0.0'
    mysql_root_password_update: true
    mysql_enabled_on_startup: true

  roles:
    - role: geerlingguy.mysql

  tasks:
    - name: Ensure MySQL is listening on all interfaces
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        state: present
      notify: Restart MySQL

  handlers:
    - name: Restart MySQL
      service:
        name: mysql
        state: restarted
